services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=123456789
      - DB_NAME=test_db
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
       - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
